# Generated by Django 2.0.4 on 2018-04-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='passwd',
            field=models.CharField(default='xMRRBiPdmLil', max_length=20),
        ),
    ]
